spring:


  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/shiro_example_db?useUnicode=true&characterEncoding=UTF-8'
    username: root
    password: root

logging:
  level:
    root: debug


mybatis:
  configuration:
    map-underscore-to-camel-case: true  #开启mybatis驼峰
